### ISSUE TITLE
Strange error while incorrect dynamic prepared statement result binding.

### ISSUE THREAD

**Issue by majcl** [seznam/SuperiorMySqlpp#14]
Example: 
1) We have two `unsigned int` columns in dynamic prepared statement result.
2) We incorrectly bind only first column, but twice, to different places.
3) Strange error occurs on updateResultBinding that `decimal` cannot be binded to `unsigned Long`
(the second type is ok - `unsigned int(10)` is actually `unsigned Long`, but this `decimal` is wrong, and also the error message misleading.

**Comment by smradCZ** [comment]
It's because `MYSQL_BIND` structure is initialized by zeros and `buffer_type` with value 0 corresponds to type `MYSQL_TYPE_DECIMAL`.

I'd made some tests and some observations on MySQL library source code, so:
- unbinded params cause storing 0/NULL values - decimal is stored as string with length 0, so it tries to store empty value that corresponds to NULL or to zero for number types
- unbinded results cause truncation on fetching - decimal is fetched as string and buffer length is set to zero

Solution: I can fix the exception message only and let the responsibility on the developer or I can check whether all binds are set. I would prefer check bind params, but on other side it adds extra overhead.

Any thoughts?

**Comment by majcl** [comment]
So, this is actually not initialized "variable" issue. IMHO undefined behaviour for not initialized "variable" is perfectly valid. I think that more detailed error with not-initialized parameter suggestion will be enough.
